version: 2.1

executors:
  circleci-node-10:
    docker:
      - image: circleci/node:10
    working_directory: ~/project/build-node-10

  circleci-node-8:
    docker:
      - image: circleci/node:8
    working_directory: ~/project/build-node-8

references:

  workspace_root: &workspace_root
    ~/project

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:

  build-node-10:
    executor: circleci-node-10
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build-node-10

  build-node-8:
    executor: circleci-node-8
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build-node-8

  test-node-10:
    executor: circleci-node-10
    steps:
      - *attach_workspace
      - run: npm test

  test-node-8:
    executor: circleci-node-8
    steps:
      - *attach_workspace
      - run: npm test

workflows:

  version: 2

  build-test:
    jobs:
      - build-node-8
      - build-node-10
      - test-node-8:
          requires:
            - build-node-8
      - test-node-10:
          requires:
            - build-node-10
